package com.myteam.sdfdsgs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class prod implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public prod() {
    }




}